### PR TITLE
Working with retrolambda

### PR DESCRIPTION
**Pull request by promeG**
Retrolambda perform the bytecode weaving after javaComplie task which will override hugo's weaving.

Change the timing of hugo's weaving task from javaComplie.dolast to dex.doFirst can solve this problem. 

#77  #78

### CODE REVIEW

**Comment by JakeWharton** [comment]
I can't tell what the change is because you reformatted a bunch of lines with four spaces instead of two. Can you reformat back to match the project style?

**Comment by promeG** [comment]
Hi Wharton,

I have modified the code format.

Thanks.

**Comment by TonyTangAndroid** [comment]
Hello Jake, might I ask when this pull request will be merged and release a new build? As for now, when I use retrolambda, I have always run into the issue that promeG mentioned. It will be highly appreciated if you are kind to do so in the near future.

**Comment by JakeWharton** [comment]
Cleaned up and merged the first two commits. I'm not sure removing library project support is needed at this time.

**Pull request closed without merging**
